Issues #5
KaiserKarel/substrace pull request #15
Opened 2022-11-14 15:14 UTC by TheCodingWombat

missing-security-doc lint working.

Test using `cargo test --test compile-test`

2022-11-14 15:16 UTC, TheCodingWombat commented
Closes #5

2022-11-14 23:56 UTC, KaiserKarel commented on .editorconfig
> +indent_size = 2
Prefer not to check it in, and instead use linters to guarantee formatting in CI.

2022-11-14 23:57 UTC, KaiserKarel commented on .gitattributes
> +*.fixed linguist-language=Rust
Should this be checked in?

2022-11-14 23:58 UTC, KaiserKarel commented on Cargo.toml
> +repository = "https://github.com/rust-lang/rust-clippy"
These fields need to be updated

2022-11-14 23:58 UTC, KaiserKarel commented on Cargo.toml
> +publish = true
Let's set publish to false until we can publish through CI

2022-11-14 23:59 UTC, KaiserKarel requested changes
Seems this PR still has a lot of files from Clippy, which should be removed.

2022-11-14 23:59 UTC, KaiserKarel commented on README.md
> +[![Clippy Test](https://github.com/rust-lang/rust-clippy/workflows/Clippy%20Test/badge.svg?branch=auto&event=push)](https://github.com/rust-lang/rust-clippy/actions?query=workflow%3A%22Clippy+Test%22
Let's use the old README for now, and remove dylint reference

2022-11-15 00:00 UTC, KaiserKarel commented on book/README.md
> +[book](src/development/infrastructure/book.md) for more information.
Entire book can be removed

2022-11-17 23:08 UTC, TheCodingWombat reviewed
I removed all unused clippy stuff

2022-11-21 10:17 UTC, KaiserKarel commented on substrace_lints/src/lib.rs
> +/// Macro used to declare a Clippy lint.
```suggestion
/// Macro used to declare a Substrace lint.
```

2022-11-21 10:17 UTC, KaiserKarel commented on substrace_lints/src/lib.rs
> +/// Macro used to declare a Clippy lint.
```suggestion
/// Macro used to declare a Substrace lint.
```

2022-11-21 11:15 UTC, KaiserKarel commented on src/driver.rs
> +}
Let's refactor all references to clippy to Substrace here for consistency.

2022-11-21 11:16 UTC, KaiserKarel commented on src/main.rs
> +const CARGO_CLIPPY_HELP: &str = r#"Substrace: Checks a package to catch common mistakes and improve your Rust code.
Same here, let's remove all references to clippy and rename to substrace

2022-11-21 11:16 UTC, KaiserKarel commented on substrace_lints/README.md
> +This crate contains Clippy lints. For the main crate, check [GitHub](https://github.com/rust-lang/rust-clippy).
Fix link and name

2022-11-21 11:16 UTC, KaiserKarel commented on substrace_lints/Cargo.toml
> +# build clippy with internal lints enabled, off by default
fix comment

2022-11-21 11:17 UTC, KaiserKarel commented on substrace_lints/src/substrace_lints/auxiliary/paths.rs
> +                        || match_def_path(cx, id, &TWOX256) {
Identity is also a dangerous hasher

2022-11-21 11:22 UTC, KaiserKarel commented on substrace_lints/src/utils/author.rs
> +    /// a `./tests/ui/new_lint.stdout` file with the generated code:
Fix references to clippy.

2022-11-21 11:24 UTC, KaiserKarel commented on substrace_utils/src/diagnostics.rs
> +}
Fix references to clippy

2022-11-21 11:25 UTC, KaiserKarel commented on substrace_utils/src/paths.rs
> +/// Preferably use the diagnostic item `sym::deref_method` where possible
Are all of these paths required for our lints?

2022-11-21 11:26 UTC, KaiserKarel commented on tests/compile-test.rs
> +    "rustc_semver",
Let's not test these lints/remove them?

2022-11-21 11:27 UTC, KaiserKarel requested changes
After addressing comments, this can be merged :)

2022-11-21 12:13 UTC, TheCodingWombat commented on tests/compile-test.rs
> +    "rustc_semver",
Indeed not necessary. Removed.

2022-11-21 12:18 UTC, TheCodingWombat commented on substrace_utils/src/paths.rs
> +/// Preferably use the diagnostic item `sym::deref_method` where possible
Most not necessary. Removed all that are not necessary for compilation.

2022-11-22 14:22 UTC, KaiserKarel approved these changes

2022-11-23 11:06 UTC, merged